- name: Gradle Android
  # You may pin to the exact commit or the version.
  # uses: Raul6469/android-gradle-action@b8fc7c7bde2562a4578b7e1bd996cc78d841638e
  uses: Raul6469/android-gradle-action@2.0.0
  with:
    # The ./gradlew command arguments
    script: 
    # Your Android license agreement id
    android-licence: # optional
